### ISSUE TITLE
Wrong document ID format: "RFCXXXX" should be "RFC XXXX"

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-rfcs#2]
* Wrong document ID format: "RFCXXXX" should be "RFC XXXX". In this case, it is just "RFC 1", not "RFC0001".

https://github.com/ietf-ribose/relaton-data-rfcs/blob/1537654d87432aa6756417bc0d884d52b44b71cc/data/RFC0001.yaml#L12-L13

See original:

https://datatracker.ietf.org/doc/html/rfc1
<img width="604" alt="Screenshot 2021-12-21 at 12 16 54 PM" src="https://user-images.githubusercontent.com/11865/146870193-899e6f7e-9e6f-4b21-9bae-b72a14d834a5.png">

**Comment by andrew2net** [comment]
fixed
